# Generated by Django 4.1 on 2022-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='할인금액'),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='dc_type',
            field=models.PositiveIntegerField(choices=[(0, '배송비 할인'), (1, '퍼센트(%) 할인'), (2, '정액 할인(KRW)')], verbose_name='타입(할인종류)'),
        ),
    ]
