# Generated by Django 4.1 on 2022-09-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_sale_amount_alter_coupontype_dc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontype',
            name='max_dc_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='조건(최대할인금액)'),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='조건(최소금액)'),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='값'),
        ),
    ]
